crypto:
  - changed-files:
      - any-glob-to-any-file: ["crates/ferrox-crypto/**"]

gateway:
  - changed-files:
      - any-glob-to-any-file: ["crates/ferrox-gateway/**"]

meta:
  - changed-files:
      - any-glob-to-any-file: ["crates/ferrox-meta/**"]

storage:
  - changed-files:
      - any-glob-to-any-file: ["crates/ferrox-storage/**"]

s3-api:
  - changed-files:
      - any-glob-to-any-file: ["crates/ferrox-s3-api/**"]

docs:
  - changed-files:
      - any-glob-to-any-file: ["docs/**", "**/*.md"]

helm:
  - changed-files:
      - any-glob-to-any-file: ["helm/**"]

terraform:
  - changed-files:
      - any-glob-to-any-file: ["terraform/**"]

ci:
  - changed-files:
      - any-glob-to-any-file: [".github/**"]
