apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferrox.fullname" . }}-credentials
  labels:
    {{- include "ferrox.labels" . | nindent 4 }}
type: Opaque
stringData:
  FERROX_ACCESS_KEY: {{ .Values.credentials.accessKey | quote }}
  FERROX_SECRET_KEY: {{ .Values.credentials.secretKey | quote }}
{{- if .Values.sseMasterKey }}
  FERROX_SSE_MASTER_KEY: {{ .Values.sseMasterKey | quote }}
{{- end }}
