apiVersion: v1
kind: Service
metadata:
  name: {{ include "ferrox.fullname" . }}
  labels:
    {{- include "ferrox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ferrox.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
{{- if .Values.tls.enabled }}
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
{{- end }}
